ansj:
  isNameRecognition: true
  isNumRecognition: true
  isQuantifierRecognition: true
  isRealName: false
  dic: user/default.dic
  dic_d1: user/stock.dic
  dic_d2: jdbc://jdbc:postgresql://localhost:5432/hunter|postgres|postgres|select name as name,nature,freq from dic
  stop: user/stop.dic
  ambiguity: user/ambiguity.dic
  synonyms: user/synonyms.dic
ansj_config: ansj_library.properties
